# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
        ver:
          description: 'Version tag'
          required: true
          type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Create version.h and tag release
  tag-rel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Version File
        run: |
            echo "#DEFINE TAYGA_VERSION \"${{ inputs.ver }}\"" > version.h
            echo "#define TAYGA_BRANCH \"main\"" >> version.h
            echo "#define TAYGA_COMMIT \"RELEASE\"" >> version.h
            git add version.h
      - name: Tag release
        run: |        
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "autogenerate release version file"
          git tag ${{ inputs.ver }}
          git push ${{ inputs.ver }}